#!/bin/bash
if [ -e /home/calculon/.audible ]
then
    AUTHCODE=`cat /home/calculon/.audible`
else
    # Use env var
    AUTHCODE=${AUTHCODE}
fi
t="$(date +%s)"
TMPARGS="/tmp/.aax2opus.executions"
while [ $# -gt 0 ]; do
    FILE=$1
    TMPFILE="/tmp/.aax2opus.tmp.txt"
    echo "Decoding $FILE with AUTHCODE $AUTHCODE..."

    ffmpeg -y -i "$FILE" 2> $TMPFILE 1> /dev/null
    ffmpeg -y -i "$FILE" -an -vcodec copy /tmp/cover.jpg > /dev/null 2>&1
    TITLE=`grep -a -m1 -h -r "title" $TMPFILE | head -1 | cut -d: -f2- | tr -d ":\"*\\/?<>|'" | xargs`
    TITLE=`echo $TITLE | sed -r 's/\(Unabridged\)//' | xargs`
    ARTIST=`grep -a -m1 -h -r "artist" $TMPFILE | head -1 | cut -d: -f2- | tr -d ":\"*\\/?<>|'" | xargs`
    GENRE=`grep -a -m1 -h -r "genre" $TMPFILE | head -1 | cut -d: -f2- | xargs`
    COMMENT=`grep -a -m1 -h -r "comment" $TMPFILE | head -1 | cut -d: -f2- | xargs`
    DATE=`grep -a -m1 -h -r "date" $TMPFILE | head -1 | cut -d: -f2- | xargs`
    BITRATE=`grep -a -m1 -h -r "bitrate" $TMPFILE | head -1 | rev | cut -d: -f 1 | rev | egrep -o [0-9]+ | xargs`
    BITRATE="${BITRATE}k"
    OUTPUT="$ARTIST - $TITLE"
    OUTPUT_DIR="/calculon/storage/audiobooks/${ARTIST}/${TITLE}"

    mkdir -p "${OUTPUT_DIR}"
    : > ${TMPARGS}
    while read -r first _ _ start _ end; do
        if [[ $first = Chapter ]]; then
            read
            read _ _ chapter
            array=($chapter)
            padded=$(printf "%02d" ${array[1]})
            pchapter="$first $padded"
            #echo "Splitting out \"$OUTPUT - ${pchapter}.opus\"."
            echo "ffmpeg -v fatal -stats -activation_bytes $AUTHCODE -i \"${FILE}\" -ss \"${start%?}\" -to \"$end\" -f wav pipe:1 </dev/null | opusenc --quiet --downmix-mono --bitrate 24 --vbr --picture /tmp/cover.jpg --artist \"${ARTIST}\" --title \"${TITLE}\" --album \"${TITLE}\" --date \"${DATE}\" --genre \"${GENRE}\" --comment \"DESCRIPTION=${COMMENT}\" --comment \"TRACKNUMBER=${padded}\" - \"${OUTPUT_DIR}/${OUTPUT} - ${pchapter}.opus\"" >> ${TMPARGS}
        fi
    done < $TMPFILE
    
    /usr/bin/parallel --nice 19 --jobs 8 --arg-file ${TMPARGS}

    rm "${TMPFILE}" "${TMPARGS}"
    mv /tmp/cover.jpg "${OUTPUT_DIR}/EmbeddedCover.jpg"

    t="$(($(date +%s)-t))"
    echo "Conversion of ${FILE} completed in ${t} seconds! Chaptered files are in ${OUTPUT_DIR}."

    shift
done
